name: "Build"
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: ['**']
jobs:
  build:
    strategy:
      matrix:
          os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v16
    - uses: cachix/cachix-action@v10
      with:
        name: kubukoz
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build --print-build-logs
    - uses: FirebaseExtended/action-hosting-deploy@v0
      if: github.ref == 'refs/heads/main'
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TODOMEDA_D9195 }}'
        channelId: live
        projectId: todomeda-d9195
    - uses: FirebaseExtended/action-hosting-deploy@v0
      if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TODOMEDA_D9195 }}'
        projectId: todomeda-d9195

